### ISSUE TITLE
ModuleNotFoundError: No module named 'oda_asr_voc'

### ISSUE THREAD

**Issue by wangb197** [CHENGEZ/Attacking-by-Aligning#1]
yolov3 Missing 'oda_asr_voc' module

**Comment by chengez** [comment]
Hi, we've added the modules for voc. But you may actually ignore these two voc modules by commenting out them in `train_asr_evl.py` when using MSCOCO.

**Comment by wangb197** [comment]
thank u reply，wish u all the best.
















At 2024-02-06 17:26:34, "CHENG, Yize" ***@***.***> wrote:

Hi, we've added the modules for voc. But you may actually ignore these two voc modules by commenting out them in train_asr_evl.py when using MSCOCO.
