### ISSUE TITLE
The weight file

### ISSUE THREAD

**Issue by Kegard** [CHENGEZ/Attacking-by-Aligning#2]
Hello！Thank you for your great work!
I want to reproduce your work, but I find that I can't find the weight when you train and evaluate, can you can you release your weight file?
Thank you for your reply!

**Comment by chengez** [comment]
Hi, so sorry for the late reply as I accidentally disabled email alearts. 

 What model weight are you referring to? If you are refering to the pretrained weights for yolo to start your training, they should be downloaded automatically if they do not exist in the workspace. If you are referring to the pretrained weight for frcnn or detr, by setting the `load_from` parameter in the config file will also enable it to be automatically downloaded. If you are refering to the weight file of the model of training on the poisoned data, it is too big to be shared on github. But considering we fixed the seed, it shouldn't be difficult to reproduce the results.

**Comment by Kegard** [comment]
Thank you for your reply! In begin, I have solve the problem.
