### ISSUE TITLE
您好，请教下攻击成功率计算

### ISSUE THREAD

**Issue by SamXiaosheng** [CHENGEZ/Attacking-by-Aligning#3]
感谢您精彩研究工作的分享，看了代码有一个疑问，关于ODA部分的ASR计算，只是单纯的计算触发器出现的框有没有被检测出来，并没有跟如果没出现触发器的时候这个框有没有被检测出来，不应该要做对比吗？如果本身这个目标框在没有后门上被检测出来，但加入了后门这个框未检测出来这样才能被计算一次攻击成功吧？

**Comment by chengez** [comment]
During testing, we only put trigger on TP bbox predictions. In other words, we patch triggers according to the bbox prediction results, not according to the ground truth. We ignore other prediction results and don't put triggers in them for calculating the ASR. So we are actually already doing what you mentioned.

**Comment by SamXiaosheng** [comment]
I see, thanks to your amazing work!
